### PR TITLE
Text field fix

### LINKED ISSUE #185: Tappable text modification field in submit tip form doesn't fill text box height

### PR DESCRIPTION
**Pull request by rxun**
- textinput field is multiline and expands as user types 
- pressing return/enter creates new line rather than unblurs
- resolves #185

### CODE REVIEW

File: c2tc-mobile/screens/TipForm.js [hunk 1]
```diff
@@ -232,7 +258,8 @@ const styles = StyleSheet.create({
     marginTop: 0
   },
   inputBodyContainerStyle: {
-    paddingBottom: 100,
+    //paddingTop: 15,
```
Comment (n3a9) [inline c2tc-mobile/screens/TipForm.js]: Remove comments
